# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: gumball-nodeport
spec:
  selector:
    app: test-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort

